version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=univalle@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80

  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_DB=proyecto_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin123
    ports:
      - 3306:3306
    volumes:
      - './mysql_data:/var/lib/mysql'